In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [5]:
%time for _ in range(10): my_arr2 = my_arr**2

CPU times: user 14.5 ms, sys: 13.5 ms, total: 28 ms
Wall time: 28.1 ms


In [6]:
%time for _ in range(10): [ i**2 for i in my_list ]

CPU times: user 2.67 s, sys: 264 ms, total: 2.93 s
Wall time: 2.99 s


In [7]:
data = np.random.randn(2, 3)
data

array([[-0.76015697,  1.50789834, -0.78322781],
       [ 0.17778978, -0.85021321,  1.49270611]])

In [12]:
np.random.randint(0, 1000, (2,3))

array([[537, 216, 229],
       [976, 585, 564]])

In [15]:
data *2 

array([[-1.52031394,  3.01579668, -1.56645562],
       [ 0.35557956, -1.70042641,  2.98541222]])

In [16]:
data.shape

(2, 3)

In [17]:
data.dtype

dtype('float64')

In [18]:
data1 = [6, 7.5, 8.0 ,0. , 1. ]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [19]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
arr2.ndim 

2

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
arr3 = np.empty((2,4))

In [26]:
n p.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [30]:
arr3 = arr1.astype(np.int64)

In [31]:
arr3.dtype

dtype('int64')

In [32]:
arr1.dtype

dtype('float64')

In [33]:
numeric_strings = np.array([1.25, -9.6, 42], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [35]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [36]:
int_arr = np.arange(10)
int_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
int_arr.astype(arr1.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [42]:
arr **2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [43]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [45]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [46]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [47]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [100]:
arr = np.arange(10)
arr_s = arr[5:8]
arr_s[2] = 99
arr

array([ 0,  1,  2,  3,  4,  5,  6, 99,  8,  9])

In [103]:
arr = np.arange(10)
arr_s = arr[5:8]
arr_s[:] = np.array([66, 77, 88])
arr

array([ 0,  1,  2,  3,  4, 66, 77, 88,  8,  9])

In [104]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [105]:
arr2d[0][2]

3